import {
    Hash,
    BookOpen,
    Code2,
    Briefcase,
    Heart,
    Music,
    Camera,
    Gamepad2,
    Coffee,
    Car,
    Home,
    Star,
    Zap,
    Target,
    Gift,
    MapPin,
    Clock,
    Users,
    DollarSign,
    ShoppingCart,
    Laptop,
    Smartphone,
    Tv,
    Headphones,
    Book,
    FileText,
    Image,
    Video,
    Bookmark,
    Tag,
    Folder,
    Archive,
    Settings,
    Globe,
    Lightbulb,
    Palette,
    Trophy,
    Calendar,
    Mail
} from "lucide-react"

export const CategoryIconMap = {
    Hash: Hash,
    BookOpen: BookOpen,
    Code2: Code2,
    Briefcase: Briefcase,
    Heart: Heart,
    Music: Music,
    Camera: Camera,
    Gamepad2: Gamepad2,
    Coffee: Coffee,
    Car: Car,
    Home: Home,
    Star: Star,
    Zap: Zap,
    Target: Target,
    Gift: Gift,
    MapPin: MapPin,
    Clock: Clock,
    Users: Users,
    DollarSign: DollarSign,
    ShoppingCart: ShoppingCart,
    Laptop: Laptop,
    Smartphone: Smartphone,
    Tv: Tv,
    Headphones: Headphones,
    Book: Book,
    FileText: FileText,
    Image: Image,
    Video: Video,
    Bookmark: Bookmark,
    Tag: Tag,
    Folder: Folder,
    Archive: Archive,
    Settings: Settings,
    Globe: Globe,
    Lightbulb: Lightbulb,
    Palette: Palette,
    Trophy: Trophy,
    Calendar: Calendar,
    Mail: Mail
}

export const categoryIconOptions = [
    { value: "Hash", label: "# ハッシュ" },
    { value: "BookOpen", label: "📖 本" },
    { value: "Code2", label: "💻 コード" },
    { value: "Briefcase", label: "💼 ビジネス" },
    { value: "Heart", label: "❤️ お気に入り" },
    { value: "Music", label: "🎵 音楽" },
    { value: "Camera", label: "📷 写真" },
    { value: "Gamepad2", label: "🎮 ゲーム" },
    { value: "Coffee", label: "☕ カフェ" },
    { value: "Car", label: "🚗 車" },
    { value: "Home", label: "🏠 ホーム" },
    { value: "Star", label: "⭐ スター" },
    { value: "Zap", label: "⚡ エネルギー" },
    { value: "Target", label: "🎯 目標" },
    { value: "Gift", label: "🎁 ギフト" },
    { value: "MapPin", label: "📍 場所" },
    { value: "Clock", label: "⏰ 時間" },
    { value: "Users", label: "👥 人" },
    { value: "DollarSign", label: "💰 お金" },
    { value: "ShoppingCart", label: "🛒 ショッピング" },
    { value: "Laptop", label: "💻 ラップトップ" },
    { value: "Smartphone", label: "📱 スマホ" },
    { value: "Tv", label: "📺 テレビ" },
    { value: "Headphones", label: "🎧 ヘッドホン" },
    { value: "Book", label: "📚 書籍" },
    { value: "FileText", label: "📄 文書" },
    { value: "Image", label: "🖼️ 画像" },
    { value: "Video", label: "🎬 動画" },
    { value: "Bookmark", label: "🔖 ブックマーク" },
    { value: "Tag", label: "🏷️ タグ" },
    { value: "Folder", label: "📁 フォルダ" },
    { value: "Archive", label: "📦 アーカイブ" },
    { value: "Settings", label: "⚙️ 設定" },
    { value: "Globe", label: "🌐 ウェブ" },
    { value: "Lightbulb", label: "💡 アイデア" },
    { value: "Palette", label: "🎨 アート" },
    { value: "Trophy", label: "🏆 成果" },
    { value: "Calendar", label: "📅 カレンダー" },
    { value: "Mail", label: "📧 メール" }
] 